version: '3.8'

services:
  frontend:
    build: .
    container_name: smart-meter-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0